pricing:
  Prisma:
    room:
      default: 1
    workspace:
      default: 2
    public:
      default: 3
  Spectrum:
    room:
      default: 11
    workspace:
      default: 12
    public: 
      default: 13

expenses:
  Prisma:
    room:
      default: 0
      27: 275
      60: 475
    workspace:
      default: 90
    public:
      default: 0
  Spectrum:
    room:
      default: 0
      27: 300
      60: 500
    workspace:
      default: 100
    public:
      default: 0

discount: 20

rooms:
- name: Test
  index: P2.123
  type: room
  building: Prisma
  floor: 2
  volume: 100
  capacity: 27
- name: Test2
  index: P2.124
  type: workspace
  building: Prisma
  floor: 2
  volume: 200
  capacity: 4
- name: Test3
  index: S2.124
  type: public
  building: Spectrum
  floor: 2
  volume: 200
  capacity: 20
