pricing:
  Prisma:
    room:
      default: 17,50
    workspace:
      default: 150
    public:
      default: 250
  Spectrum:
    room:
      default: 20
    workspace:
      default: 120
    public: 
      default: 250
  External:
    public: 
      default: 250

expenses:
  Prisma:
    room:
      default: 0
      27: 275
      60: 475
    workspace:
      default: 90
    public:
      default: 0
  Spectrum:
    room:
      default: 0
      27: 300
      60: 500
    workspace:
      default: 100
    public:
      default: 0
  External:
    public: 
      default: 0

discount: 20

rooms:
- name: ICT lokaal
  index: P2.167
  type: room
  building: Prisma
  floor: 2
  volume: 500
  capacity: 60
- name: Overlegruimte
  index: S0.096
  type: workspace
  building: Spectrum
  floor: 0
  volume: 45
  capacity: 4
- name: Bowling
  index: E0.000
  type: public
  building: External
  floor: 0
  volume: 20
  capacity: 10
